version: "3.8"

services:

  onpt-frontend:
    build:
      context: ../../onpt-website-frontend
      dockerfile: Dockerfile
    hostname: onpt-frontend
    container_name: onpt-frontend
    tty: true
    env_file:
      - ".env"
    environment:
      NEXT_PUBLIC_BACKEND_API_URL: "http://localhost:1337"
      SERVICE_NAME: onpt-frontend
      SERVICE_TAGS: production
    stdin_open: true
    networks:
      - internal-network
      - external-network
    links:
      - onpt-backend
    depends_on:
      - onpt-backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.onpt-frontend.rule=Host(`ordre.pharmaciens.tg`,`www.pharmaciens.tg`,`pharmaciens.tg`,`www.ordre.pharmaciens.tg`,`onpt.pharmaciens.tg`,`www.onpt.pharmaciens.tg`)'
      - 'traefik.http.routers.onpt-frontend-secure.rule=Host(`ordre.pharmaciens.tg`,`www.pharmaciens.tg`,`pharmaciens.tg`,`www.ordre.pharmaciens.tg`,`onpt.pharmaciens.tg`,`www.onpt.pharmaciens.tg`)'
      - "traefik.http.routers.onpt-frontend.entrypoints=web,websecure"
      - "traefik.port=80"
      - "traefik.http.routers.onpt-frontend.tls=true"
      - "traefik.http.routers.onpt-frontend.tls.certresolver=lets-encrypt"

  onpt-backend:
    build:
      context: ../../onpt-website-backend
      dockerfile: Dockerfile.prod
    container_name: onpt-backend
    restart: unless-stopped
    volumes:
      - ../../onpt-website-backend/public:/app/public
      - ../../onpt-website-backend/config:/app/config
      - ../../onpt-website-backend/src:/app/src
      - ../../onpt-website-backend/package.json:/app/package.json
      - ../../onpt-website-backend/.env:/app/.env
      - ../../onpt-website-backend/public/uploads:/app/public/uploads
    env_file:
      - ".env"
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: ${MYSQL_HOST}
      DATABASE_PORT: ${MYSQL_PORT}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_SSL: false
      DATABASE_AUTHENTICATION_DATABASE: ${MYSQL_DATABASE}
      SERVICE_TAGS: production
    networks:
      - internal-network
      - external-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.onpt-backend.rule=Host(`admin.pharmaciens.tg`,`panel.pharmaciens.tg`,`www.admin.pharmaciens.tg`,`www.panel.pharmaciens.tg`)'
      - 'traefik.http.routers.onpt-backend-secure.rule=Host(`admin.pharmaciens.tg`,`panel.pharmaciens.tg`,`www.admin.pharmaciens.tg`,`www.panel.pharmaciens.tg`)'
      - "traefik.http.routers.onpt-backend.entrypoints=web,websecure"
      - "traefik.port=80"
      - "traefik.http.routers.onpt-backend.tls=true"
      - "traefik.http.routers.onpt-backend.tls.certresolver=lets-encrypt"

volumes:
  sessions:

networks:
  internal-network:
    name: internal-network
    driver: bridge

  external-network:
    external: true